In [1]:
typeof(4)

Int64

In [2]:
a = typeof(4)

Int64

In [3]:
typeof(a)

DataType

In [4]:
typeof(DataType)

DataType

In [6]:
b = supertype(a)

Signed

In [7]:
supertype(b)

Integer

In [8]:
supertype(UInt64)

Unsigned

In [9]:
supertype(Integer)

Real

In [10]:
supertype(Real)

Number

In [11]:
supertype(Number)

Any

In [12]:
for i in 1:10
    a = supertype(a)
    println(a)
end

Signed
Integer
Real
Number
Any
Any
Any
Any
Any
Any


In [13]:
print("hello")
print(" world")

hello world

In [16]:
println("hello")
print(" world")

hello
 world

In [17]:
subtypes(Int64)

0-element Array{Type,1}

In [18]:
"x" * "x" # concatenation

"xx"

In [19]:
"x" + "x"

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529

In [20]:
"x" ^ 3

"xxx"

In [21]:
function showtypetree(T, level=0)
    println("\t" ^ level, T)
    for t in subtypes(T)
        if t != Any
            showtypetree(t, level+1)
        end
    end
end

showtypetree (generic function with 2 methods)

In [42]:
showtypetree(Number)

Number
	Complex
	Real
		AbstractFloat
			BigFloat
			Float16
			Float32
			Float64
		AbstractIrrational
			Irrational
		Integer
			Bool
			Signed
				BigInt
				Int128
				Int16
				Int32
				Int64
				Int8
			Unsigned
				UInt128
				UInt16
				UInt32
				UInt64
				UInt8
		Rational


In [24]:
showtypetree(Bool)

Bool


In [25]:
showtypetree(String)

String


In [26]:
showtypetree(AbstractString)

AbstractString
	String
	SubString
	SubstitutionString
	Test.GenericString


In [29]:
sizeof("abc ") # number bytes

4

In [30]:
length("abc ") # number characters

4

In [31]:
sizeof(3)

8

In [32]:
sizeof(Int16(3))

2

In [33]:
length(3)

1

In [34]:
sizeof(Int32)

4

In [36]:
sizeof(Int128)

16

In [37]:
sizeof(Bool)

1

In [38]:
sizeof(Integer)

ErrorException: Abstract type Integer does not have a definite size.

In [39]:
typeof(Number)

DataType

In [40]:
typeof(DataType)

DataType

In [43]:
field

UndefVarError: UndefVarError: field not defined

In [48]:
?fieldnames

search: fieldnames fieldname



```
fieldnames(x::DataType)
```

Get a tuple with the names of the fields of a `DataType`.

# Examples

```jldoctest
julia> fieldnames(Rational)
(:num, :den)
```


In [54]:
typeof(5:8)

UnitRange{Int64}

In [55]:
typeof(UnitRange)

UnionAll

In [56]:
typeof(UnionAll)

DataType

In [57]:
showtypetree(DataType)

DataType


In [58]:
showtypetree(UnitRange)

UnitRange


In [59]:
typeof(5:2:8)

StepRange{Int64,Int64}

In [60]:
typeof(StepRange)

UnionAll

In [61]:
(5:2:8).start

5

In [62]:
(5:2:8).step

2

In [63]:
(5:2:8).stop # ends at 7, not 8 due to step size

7

In [64]:
d = Dict("one" => 1, "two" => 2, "three" => 3)

Dict{String,Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [65]:
typeof(d)

Dict{String,Int64}

In [66]:
typeof(Dict)

UnionAll

In [67]:
d.count

3

In [68]:
d.vals

16-element Array{Int64,1}:
 0
 0
 0
 0
 0
 2
 0
 0
 0
 0
 0
 1
 3
 0
 0
 0

In [69]:
d.keys

16-element Array{String,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
    "two"
 #undef
 #undef
 #undef
 #undef
 #undef
    "one"
    "three"
 #undef
 #undef
 #undef

In [70]:
5:8

5:8

In [71]:
first(5:8)

5

In [72]:
step(5:8)

1

In [73]:
last(5:8)

8

In [74]:
step(5:2:8)

2

In [14]:
typeof(BigInt)

DataType

In [15]:
supertype(BigInt)

Signed

In [16]:
typeof(DataType)

DataType

In [17]:
subtypes(BigInt)

0-element Array{Type,1}

In [18]:
typeof(Signed)

DataType