In [1]:
read

read (generic function with 43 methods)

In [2]:
?read

search: read read! readdir readlink readline readuntil readlines readchomp



```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String`.

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [5]:
s = readline("elements.txt")

"# Atomic Num\tName\t\tSymbol\tAtomic mass"

In [6]:
s = readlines("elements.txt")

5-element Array{String,1}:
 "# Atomic Num\tName\t\tSymbol\tAtomic mass"
 "1\t\tHydrogen\tH\t1.007825"
 "2\t\tHelium\t\tHe\t4.00260"
 "3\t\tLithium\t\tLi\t6.941"
 "4\t\tBeryllium\tBe\t9.01218"

In [7]:
println(s)

["# Atomic Num\tName\t\tSymbol\tAtomic mass", "1\t\tHydrogen\tH\t1.007825", "2\t\tHelium\t\tHe\t4.00260", "3\t\tLithium\t\tLi\t6.941", "4\t\tBeryllium\tBe\t9.01218"]


In [8]:
typeof(s)

Array{String,1}

In [9]:
typeof(Array)

UnionAll

In [10]:
stream = open("elements.txt", "r")

IOStream(<file elements.txt>)

In [11]:
typeof(IOStream)

DataType

In [12]:
supertype(IOStream)

IO

In [13]:
supertype(IO)

Any

In [19]:
eof(stream)

false

In [20]:
position(stream)

0

In [21]:
read(stream, Char)

'#': ASCII/Unicode U+0023 (category Po: Punctuation, other)

In [22]:
readline(stream)

" Atomic Num\tName\t\tSymbol\tAtomic mass"

In [24]:
position(stream)

38

In [27]:
read(stream, Int8)

49

In [26]:
Char(51)

'3': ASCII/Unicode U+0033 (category Nd: Number, decimal digit)

In [29]:
eof(stream) # is it the end of the file?

false

In [30]:
readlines(stream)

4-element Array{String,1}:
 "\t\tHydrogen\tH\t1.007825"
 "2\t\tHelium\t\tHe\t4.00260"
 "3\t\tLithium\t\tLi\t6.941"
 "4\t\tBeryllium\tBe\t9.01218"

In [31]:
eof(stream)

true

In [33]:
close(stream) # remember to close the file

In [34]:
?open

search: open isopen propertynames CompositeException operm hasproperty



```
open(f::Function, args...; kwargs....)
```

Apply the function `f` to the result of `open(args...; kwargs...)` and close the resulting file descriptor upon completion.

# Examples

```jldoctest
julia> open("myfile.txt", "w") do io
           write(io, "Hello world!")
       end;

julia> open(f->read(f, String), "myfile.txt")
"Hello world!"

julia> rm("myfile.txt")
```

---

```
open(filename::AbstractString; keywords...) -> IOStream
```

Open a file in a mode specified by five boolean keyword arguments:

| Keyword    | Description            | Default                               |
|:---------- |:---------------------- |:------------------------------------- |
| `read`     | open for reading       | `!write`                              |
| `write`    | open for writing       | `truncate \| append`                  |
| `create`   | create if non-existent | `!read & write \| truncate \| append` |
| `truncate` | truncate to zero size  | `!read & write`                       |
| `append`   | seek to end            | `false`                               |

The default when no keywords are passed is to open files for reading only. Returns a stream for accessing the opened file.

---

```
open(filename::AbstractString, [mode::AbstractString]) -> IOStream
```

Alternate syntax for open, where a string-based mode specifier is used instead of the five booleans. The values of `mode` correspond to those from `fopen(3)` or Perl `open`, and are equivalent to setting the following boolean groups:

| Mode | Description                   | Keywords                       |
|:---- |:----------------------------- |:------------------------------ |
| `r`  | read                          | none                           |
| `w`  | write, create, truncate       | `write = true`                 |
| `a`  | write, create, append         | `append = true`                |
| `r+` | read, write                   | `read = true, write = true`    |
| `w+` | read, write, create, truncate | `truncate = true, read = true` |
| `a+` | read, write, create, append   | `append = true, read = true`   |

# Examples

```jldoctest
julia> io = open("myfile.txt", "w");

julia> write(io, "Hello world!");

julia> close(io);

julia> io = open("myfile.txt", "r");

julia> read(io, String)
"Hello world!"

julia> write(io, "This file is read only")
ERROR: ArgumentError: write failed, IOStream is not writeable
[...]

julia> close(io)

julia> io = open("myfile.txt", "a");

julia> write(io, "This stream is not read only")
28

julia> close(io)

julia> rm("myfile.txt")
```

---

```
open(fd::OS_HANDLE) -> IO
```

Take a raw file descriptor wrap it in a Julia-aware IO type, and take ownership of the fd handle. Call `open(Libc.dup(fd))` to avoid the ownership capture of the original handle.

!!! warn
    Do not call this on a handle that's already owned by some other part of the system.


---

```
open(command, mode::AbstractString, stdio=devnull)
```

Run `command` asynchronously. Like `open(command, stdio; read, write)` except specifying the read and write flags via a mode string instead of keyword arguments. Possible mode strings are:

| Mode | Description | Keywords                    |
|:---- |:----------- |:--------------------------- |
| `r`  | read        | none                        |
| `w`  | write       | `write = true`              |
| `r+` | read, write | `read = true, write = true` |
| `w+` | read, write | `read = true, write = true` |

---

```
open(command, stdio=devnull; write::Bool = false, read::Bool = !write)
```

Start running `command` asynchronously, and return a `process::IO` object.  If `read` is true, then reads from the process come from the process's standard output and `stdio` optionally specifies the process's standard input stream.  If `write` is true, then writes go to the process's standard input and `stdio` optionally specifies the process's standard output stream. The process's standard error stream is connected to the current global `stderr`.

---

```
open(f::Function, command, args...; kwargs...)
```

Similar to `open(command, args...; kwargs...)`, but calls `f(stream)` on the resulting process stream, then closes the input stream and waits for the process to complete. Returns the value returned by `f`.


In [35]:
open(readline, "elements.txt")

"# Atomic Num\tName\t\tSymbol\tAtomic mass"

In [36]:
open(readlines, "elements.txt")

5-element Array{String,1}:
 "# Atomic Num\tName\t\tSymbol\tAtomic mass"
 "1\t\tHydrogen\tH\t1.007825"
 "2\t\tHelium\t\tHe\t4.00260"
 "3\t\tLithium\t\tLi\t6.941"
 "4\t\tBeryllium\tBe\t9.01218"

In [38]:
@edit readlines("elements.txt") # edit macro

In [39]:
myread(s::IOStream) = read(s, Char)

myread (generic function with 1 method)

In [40]:
open(myread, "elements.txt")

'#': ASCII/Unicode U+0023 (category Po: Punctuation, other)

In [41]:
@edit open(myread, "elements.txt")

In [42]:
open("elements.txt") do stream  # do stream = function I'm passing in
    for line in eachline(stream)
        print(line)
    end
end

# Atomic Num	Name		Symbol	Atomic mass1		Hydrogen	H	1.0078252		Helium		He	4.002603		Lithium		Li	6.9414		Beryllium	Be	9.01218

In [43]:
function f(stream)
    for line in eachline(stream)
        print(line)
    end
end

f (generic function with 1 method)

In [44]:
open(f, "elements.txt") # our own function is passed in

# Atomic Num	Name		Symbol	Atomic mass1		Hydrogen	H	1.0078252		Helium		He	4.002603		Lithium		Li	6.9414		Beryllium	Be	9.01218

In [45]:
?eachline

search: eachline eachslice



```
eachline(io::IO=stdin; keep::Bool=false)
eachline(filename::AbstractString; keep::Bool=false)
```

Create an iterable `EachLine` object that will yield each line from an I/O stream or a file. Iteration calls [`readline`](@ref) on the stream argument repeatedly with `keep` passed through, determining whether trailing end-of-line characters are retained. When called with a file name, the file is opened once at the beginning of iteration and closed at the end. If iteration is interrupted, the file will be closed when the `EachLine` object is garbage collected.

# Examples

```jldoctest
julia> open("my_file.txt", "w") do io
           write(io, "JuliaLang is a GitHub organization.\n It has many members.\n");
       end;

julia> for line in eachline("my_file.txt")
           print(line)
       end
JuliaLang is a GitHub organization. It has many members.

julia> rm("my_file.txt");
```


In [46]:
write("foobar.txt", "Hello world")

11

In [48]:
open(readlines, "foobar.txt")

1-element Array{String,1}:
 "Hello world"

In [49]:
write("numbar.txt", 42) # 42 gets parsed as ascii -> "*"

8

In [50]:
open(readlines, "numbar.txt")

1-element Array{String,1}:
 "*\0\0\0\0\0\0\0"

In [51]:
write("numbar2.txt", string(42))

2

In [55]:
open("alpha.txt", "w") do io # overwrite
    for ch in 'A':'Z'
        write(io, ch)
    end
    write(io, "\n")
end

1

In [56]:
open("alpha.txt", "a") do io # append
    for ch in 'A':'Z'
        write(io, ch)
    end
    write(io, "\n")
end

1

In [52]:
typeof('A')

Char

In [53]:
typeof("A")

String

In [57]:
STDIN

UndefVarError: UndefVarError: STDIN not defined